services:
  - type: postgresql
    name: genealogy-db
    plan: free

  - type: web
    name: genealogy-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn genealogy.wsgi:application
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: genealogy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DISABLE_COLLECTSTATIC
        value: "1"